name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm ci
      - name: Find Dead Code
        run: npm run find-deadcode
      - name: Run Lint
        run: npm run lint
      - name: Run Type Check
        run: npm run typecheck

  # trigger-cd:
  #   needs: ci
  #   uses: ./.github/workflows/cd-vercel.yml
  #   # uses: ./.github/workflows/cd-cluster.yml
  #   secrets: inherit
